<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE namelist [
<!ELEMENT names (name)>
<!ELEMENT name (#PCDATA)>
]>

<names>

 <name>Bob</name>
 <name>Jane</name>
 <name>Sam</name>
 <name>Jim</name>
 <name>Andy</name>
 <name>Ben</name>
 <name>ShotGlass</name>
 <name>Dingus</name>
 <name>Jason</name>
 <name>Shoe</name>
 <name>Cliche</name>
 <name>NotDrunk</name>
 <name>WillYouMarryMe</name>
 
 <name>John</name></names>