<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE namelist [
<!ELEMENT namelist (name)*>
<!ELEMENT name (#PCDATA)>
]>

<namelist>

    <name>Amy</name>
    <name>DothNotSerious</name>
    <name>Bob</name>
    <name>Jane</name>
    <name>Mr.Pin</name>
    <name>MichellJackson</name>
    <name>John</name>
    <name>Sam</name>
    <name>Pukachu</name>
    <name>Jim</name>
    <name>JustABeaver</name>
    <name>DarthBeggar</name>
    <name>Flinthome</name>
    <name>Pilarry</name>
    <name>Dr.Wevil</name>
    <name>Gypschikic</name>
    <name>Bristle</name>
    <name>Notlikethis</name>
    <name>Bastardora</name>
    <name>DeSantaClaws</name>
    <name>Triton</name>
    <name>Andy</name>
    <name>Willie</name>
    <name>Johnson</name>
    <name>Ben</name>
    <name>Hitter</name>
    <name>ShotGlass</name>
    <name>Dingus</name>
    <name>GeneralPurpose</name>
    <name>Nagito</name>
    <name>Hairy</name>
    <name>Donnie</name>
    <name>Tramp</name>
    <name>Jason</name>
    <name>Shoe</name>
    <name>Cliche</name>
    <name>NotDrunk</name>
    <name>Willy</name>
    <name>WillYouMarryMe</name>
    <name>BatFastard</name>
    <name>Stanleia</name>
    <name>Austin'sDangerousPowers</name>
    <name>GaiSpelledInkorrectly</name>
    <name>RobingHoop</name>
    <name>AnonimousGuardWithoutANametag</name>
    <name>BobDahBuildah</name>
    <name>BuySahnePudding</name>
    <name>Larry</name>
    <name>Barry</name>
    <name>Marry</name>
    <name>Harry</name>
    <name>Carry</name>
    <name>Narry</name>
    <name>OtherNamesEndingWith:arry</name>
    <name>ImGettingABitBoredOfTypingNames</name>
    <name>Dr.Who</name>
    <name>Dr.What</name>
    <name>Dr.Why</name>
    <name>Dr.When</name>
    <name>Dr.Where</name>
    <name>Name</name>
    <name>I'mSurprisedYouMadeItThisFar</name>
    <name>NowTheNamesWillStartRepeating</name>

</namelist>
